### ISSUE TITLE
Create a readme, docs and publish

### ISSUE THREAD

**Issue by AlvinKuruvilla** [pirtleshell/rust-gedcom#1]
This is a cool project you should do docs for this and publish it to crates.io

**Comment by pirtleshell** [comment]
hey! thanks, i appreciate it! it's still rather incomplete which is why i have not done any of those things, but i agree that it needs a readme. i suppose i could publish this incomplete version on crates, too.

thanks for the feedback!

**Comment by AlvinKuruvilla** [comment]
Oh you should post a to-do list and I can always try and contribute to the
crate, and I'm sure that might attract other people too.
I'm still pretty new but I will try my best to contribute

**Comment by pirtleshell** [comment]
Thanks again for giving me the motivation and incentive to do this. I've published the current (albeit incomplete) code to crates: https://crates.io/crates/gedcom

**Comment by AlvinKuruvilla** [comment]
No problem, can you also add a todo list to the repo for the features or
things that need to be added or changed to the crate? I’d love to try and
contribute

**Comment by pirtleshell** [comment]
Unfortunately there are probably too many to list. I make note of the top-level tags that are not currently handled [in the readme](https://github.com/pirtleshell/rust-gedcom#top-level-tags) (handling Multimedia or Notes would probably be the next to tackle).

The simplest and easiest way to contribute would be to take a gedcom file, attempt to parse it and see what tags you run into that are not accounted for. For a more systematic approach, you could take a tag and check [the spec](https://edge.fscdn.org/assets/img/documents/ged551-5bac5e57fe88dd37df0e153d9c515335.pdf) to see what subtags are left unhandled in the [parser](https://github.com/pirtleshell/rust-gedcom/blob/master/src/parser.rs) or [types](https://github.com/pirtleshell/rust-gedcom/tree/master/src/types).

Another option for contribution could be to write some tests, as I only have some pretty basic ones written.

I'd happily take a look at any PR! Thanks for your interest!!
