### ISSUE TITLE
Add support for instantiating a new parser from a string representation of the data in a gedcom file

### ISSUE THREAD

**Issue by AlvinKuruvilla** [pirtleshell/rust-gedcom#3]
I think it would be nice for the parser api to include a way for the user to provide just the string representation of the data in a gedcom file 

Also do you think it's a good idea for there to a way for a parser to be instantiated given the path to a gedcom file?

**Comment by pirtleshell** [comment]
Hiya!

I'd like to keep the build size as small as possible, so I think reading a file from a path is too much for the library part of the code. The binary that is generated accepts a path and reads the file accordingly. To get a file to a string is a one-liner that I think shouldn't be too much trouble for a consumer of the library to write:
`let gedcom_contents = std::fs::read_to_string(absolute_path).unwrap();`

As for the parsing from a `String`, I also think being opinionated about the input is beneficial. To pass in a character iterator, one needs to simple call `.chars()` on their string. It is more flexible in how a user can get the iterator and simple enough to convert from a string that I don't think a new method is warranted.

Thanks!

**Comment by AlvinKuruvilla** [comment]
Okay that's good to know I am going to submit a PR soon about some very basic logging with the log crate
